### PR TITLE
Compatibility Python 3 (only)

### PR DESCRIPTION
**Pull request by olivierverdier**
Nose progressive did not work with Python 3 for me before I made those changes. I'm aware that they probably break Python 2 compatibility though.

### CODE REVIEW

**Comment by jonathan-s** [comment]
I'm curious what errors you got?

**Comment by olivierverdier** [comment]
It was such a long time ago, I don't remember. Now I use py.test anyway, as [nose is being deprecated](http://nose.readthedocs.io/en/latest/#). Perhaps this PR should even be closed.

**Comment by erikrose** [comment]
I'm open to merging this (I have yet to really look at it), but I'd also like to port nose-progressive to py.test for the future. py.tests's default output is uniquely horrible. :-)

**Comment by olivierverdier** [comment]
@erikrose, first, thanks so much for this package. I have used it a lot the past few years.

However, I have now moved on to py-test, and do not use nose at all anymore (besides, py-test is compatible with nose). I really hope that you port nose-progressive to py-test though!

Anyway, for this reason, I lack the motivation to work on this PR, and I am closing it. Feel free to use it as a starting point to make nose-progressive compatible with Python 3 though.

**Comment by erikrose** [comment]
Thanks for identifying the spots that need to be fixed!

**Pull request closed without merging**
